# Build the database from calendars

1. Update the folder
2. From the previous year get the update_users.csv and updated_groups.csv files and rename them as users.csv and groups.csv
3. Make sure the folder contains the calendars.csv, users.csv, groups.csv
4. Open one of the calendar and copy the cookie in the cookie.txt file

In [1]:
%load_ext autoreload
%autoreload 2

In [1]:
from pathlib import Path
import pandas as pd

# UPDATE THE FOLDER HERE
folder = Path('/run/user/1000/gvfs/smb-share:server=istore,share=microscopy_group_share,user=jeromeb/Admin/Usage Stats/2026')

db_file = folder / 'bookings.db'

booking_types = ['default','service', 'maintenance', 'training']
divisions = ['Unknown','Cell Biology','Neurobiology','PNAC','Structural Studies','University']
groups = pd.read_csv(folder/'groups.csv')
users = pd.read_csv(folder/'users.csv')
calendars = pd.read_csv(folder/'calendars.csv')

# get a cookie from the curl command copied from firefox dev tools and save it in a cookie.txt file
with open('cookie.txt','r') as f:
    curl_str = f.read()

print(f"there are {len(calendars)} instruments")

there are 29 instruments

In [2]:
# check that the calendars url are uniques
assert calendars['url'].is_unique, "Calendar URLs are not unique!"

In [5]:
calendars = calendars[calendars['instrument']!="Zeiss Analysis PC"]

## Update or initialize the database.

- Load all the calendars into the database.

In [6]:
from usagestats.bookingdb import BookingDB

with BookingDB(db_file, curl_str=curl_str) as bookings:
    bookings.create_calendars_from_df(calendars)
    bookings.create_instruments()
    bookings.create_booking_types(booking_types)
    bookings.create_division(divisions)
    bookings.create_groups(groups)
    df, duplicates = bookings.create_events(users)

UNIQUE constraint failed: calendars.url
UNIQUE constraint failed: calendars.url
UNIQUE constraint failed: calendars.url
UNIQUE constraint failed: calendars.url
UNIQUE constraint failed: calendars.url
UNIQUE constraint failed: calendars.url
UNIQUE constraint failed: calendars.url
UNIQUE constraint failed: calendars.url
UNIQUE constraint failed: calendars.url
UNIQUE constraint failed: calendars.url
UNIQUE constraint failed: calendars.url
UNIQUE constraint failed: calendars.url
UNIQUE constraint failed: calendars.url
UNIQUE constraint failed: calendars.url
UNIQUE constraint failed: calendars.url
UNIQUE constraint failed: calendars.url
UNIQUE constraint failed: calendars.url
UNIQUE constraint failed: calendars.url
UNIQUE constraint failed: calendars.url
UNIQUE constraint failed: calendars.url
UNIQUE constraint failed: calendars.url
UNIQUE constraint failed: calendars.url
UNIQUE constraint failed: calendars.url
UNIQUE constraint failed: calendars.url
UNIQUE constraint failed: calendars.url
UNIQUE constraint failed: calendars.url
UNIQUE constraint failed: calendars.url
UNIQUE constraint failed: calendars.url
Analysis PC1
Analysis PC2
Analysis PC3
Analysis PC4
Andor BC43
Leica SP8
Leica STED
Nanoimager
Nikon HCA
Nikon ISIM
Nikon NSTORM
Nikon TI2
Nikon TIRF
Nikon W1
Olympus VS200
Olympus VS200
OPM
Spinning Disk
Zeiss 2p
Zeiss 710
Zeiss 710 upright
Zeiss 780
Zeiss 780 UV
Zeiss 880 Airyscan
Zeiss 900 Airyscan AI
Zeiss AxioImager
Zeiss Axioplan
Zeiss Elyra
Zeiss Analysis PC

Analysis of duplicates at all time

In [14]:
pd.concat(df[df['guid']==x].iloc[0].to_frame().T for x in duplicates).groupby('user')['hours'].agg(['count','sum'])

                 count     sum
user
Ana Crespillo       13    58.0
Ben Sutcliffe      188  2647.5
Gerard Crossan       1     3.0
Luca Schwarz         1     1.5
Nathan Richoz        1     1.0
Nathaniel Hoyle      1    73.0

## Update user information

In [49]:
with BookingDB(db_file, curl_str=curl_str) as bookings:
    users = bookings.get_users()
users

                      name                       email             group
0            Nathan Richoz   nrichoz@mrc-lmb.cam.ac.uk        Clatworthy
1            Ben Sutcliffe  sutcliff@mrc-lmb.cam.ac.uk  Light Microscopy
2    Michal Eisenberg-Bord  michaleb@mrc-lmb.cam.ac.uk    Ramakrishnan L
3            Antonio Pagan    apagan@mrc-lmb.cam.ac.uk    Ramakrishnan L
4          Ping-Huang Tsai    phtsai@mrc-lmb.cam.ac.uk        Clatworthy
..                     ...                         ...               ...
692       Elizabeth Miller   emiller@mrc-lmb.cam.ac.uk           Unknown
693            Sahar Emran    semran@mrc-lmb.cam.ac.uk           Unknown
694         Paul Edelstein     paule@mrc-lmb.cam.ac.uk           Unknown
695      Jonathan Shanahan  shanahan@mrc-lmb.cam.ac.uk           Unknown
696           Jakub Luptak   jluptak@mrc-lmb.cam.ac.uk           Unknown

[697 rows x 3 columns]