# Add new users in the database

Before running this notebook:
1. Update the folder
2. Update the start date 

- Load the data base
- Get the unique users for this year and find the on without group
- Edit the new users.csv file to add the id of the groups
-

In [ ]:
from usagestats.bookingdb import BookingDB
from datetime import datetime, timedelta
import pytz
import pandas as pd
from pathlib import Path
local_tz = pytz.timezone("Europe/London")

# UPDATE THE FOLDER HERE
folder = Path('/run/user/1000/gvfs/smb-share:server=istore,share=microscopy_group_share,user=jeromeb/Admin/Usage Stats/2025')
# UPDATE THE DATE HERE
start_date = datetime.fromisoformat('2024-11-04').replace(tzinfo=local_tz)
end_date =  start_date + timedelta(weeks=52) # iso-format data yyyy-mm-dd


db_file = folder / 'bookings.db'

remove_bookings_type = ['service', 'maintenance']
remove_instrument = ['Analysis pc1','Analysis pc2' ,'Analysis pc3' ,'Analysis pc4','Zeiss sim analysis pc']

with BookingDB(db_file) as db:
    bookings = db.get_events_in_range(start_date, end_date)

newusers = bookings[bookings['group']=='Unknown'][['email', 'user','group','division']].drop_duplicates().reset_index()
print(f"Number of new users: {len(newusers)}")

# save the list to a csv file
new_users_path = folder/'new users.csv'

if not new_users_path.exists():
    newusers.to_csv(folder/'new users.csv')
else:
    print(f"File '{new_users_path.name}' exists.")
newusers

Number of new users: 3
File 'new users.csv' exists.

   index            user    group division
0   1745          Fei Wu  Unknown  Unknown
1   6464    Sophia Arana  Unknown  Unknown
2   6805  Héctor Pizarro  Unknown  Unknown

Load the new users csv file with the added information and update the booking database with group information creating users and groups if needed.

In [104]:
newusers = pd.read_csv(folder/'new users_bak.csv',index_col=0)

with BookingDB(db_file) as db:
    db.update_users_group_from_df(newusers)

# Check the remaining unknown users
with BookingDB(db_file) as db:
    unique_users = db.get_unique_users_in_range(start_date, end_date)
unique_users[unique_users['group']=='Unknown']

               name                       email    group division
87           Fei Wu        fw@mrc-lmb.cam.ac.uk  Unknown  Unknown
187    Sophia Arana    sarana@mrc-lmb.cam.ac.uk  Unknown  Unknown
190  Héctor Pizarro  hpizarro@mrc-lmb.cam.ac.uk  Unknown  Unknown

Update the groups.csv and users.csv for next time.

In [105]:

begin_of_time = datetime.fromisoformat('2022-11-04').replace(tzinfo=local_tz)
with BookingDB(db_file) as db:
    users = db.get_unique_users_in_range(begin_of_time, end_date)

users[['name','group']].rename(columns={'name':'user'}).to_csv(folder/"updated_users.csv")
users[['group','division']].drop_duplicates().to_csv(folder/"updated_groups.csv")